export type Destination = {
  city: string;
  country: string;
  highlight: string;
};

export const destinations: Destination[] = [
  { city: "Amsterdam", country: "Netherlands", highlight: "canals, museums, and cycling routes" },
  { city: "Athens", country: "Greece", highlight: "ancient ruins, island access, and Mediterranean food" },
  { city: "Auckland", country: "New Zealand", highlight: "harbors, islands, and outdoor adventures" },
  { city: "Bali", country: "Indonesia", highlight: "beaches, rice terraces, and wellness retreats" },
  { city: "Bangkok", country: "Thailand", highlight: "street food, temples, and affordable stays" },
  { city: "Barcelona", country: "Spain", highlight: "architecture, beaches, and tapas" },
  { city: "Beijing", country: "China", highlight: "historic landmarks, food streets, and cultural sites" },
  { city: "Berlin", country: "Germany", highlight: "history, nightlife, and creative neighborhoods" },
  { city: "Boston", country: "United States", highlight: "history, campuses, and harbor walks" },
  { city: "Buenos Aires", country: "Argentina", highlight: "tango, steak, and grand avenues" },
  { city: "Cairo", country: "Egypt", highlight: "pyramids, museums, and Nile views" },
  { city: "Cape Town", country: "South Africa", highlight: "mountains, beaches, and wine country" },
  { city: "Chennai", country: "India", highlight: "temples, beaches, and South Indian food" },
  { city: "Chicago", country: "United States", highlight: "architecture, museums, and lakefront walks" },
  { city: "Copenhagen", country: "Denmark", highlight: "design, canals, and calm city life" },
  { city: "Delhi", country: "India", highlight: "monuments, markets, and North Indian food" },
  { city: "Doha", country: "Qatar", highlight: "museums, desert trips, and waterfront views" },
  { city: "Dubai", country: "United Arab Emirates", highlight: "shopping, skyline views, and desert experiences" },
  { city: "Dublin", country: "Ireland", highlight: "pub culture, literary history, and coastal day trips" },
  { city: "Edinburgh", country: "United Kingdom", highlight: "castles, festivals, and old town walks" },
  { city: "Florence", country: "Italy", highlight: "art, architecture, and Tuscan food" },
  { city: "Goa", country: "India", highlight: "beaches, seafood, and relaxed nightlife" },
  { city: "Hanoi", country: "Vietnam", highlight: "old quarter walks, coffee, and street food" },
  { city: "Hong Kong", country: "China", highlight: "harbor views, dim sum, and shopping" },
  { city: "Istanbul", country: "Turkey", highlight: "bazaars, mosques, and Bosphorus views" },
  { city: "Jaipur", country: "India", highlight: "palaces, forts, and colorful markets" },
  { city: "Kochi", country: "India", highlight: "backwaters, heritage streets, and seafood" },
  { city: "Kuala Lumpur", country: "Malaysia", highlight: "city sights, food courts, and easy day trips" },
  { city: "Kyoto", country: "Japan", highlight: "temples, gardens, and traditional streets" },
  { city: "Lisbon", country: "Portugal", highlight: "viewpoints, trams, and coastal food" },
  { city: "London", country: "United Kingdom", highlight: "museums, theatre, and iconic landmarks" },
  { city: "Los Angeles", country: "United States", highlight: "beaches, film culture, and food scenes" },
  { city: "Madrid", country: "Spain", highlight: "art museums, parks, and tapas" },
  { city: "Maldives", country: "Maldives", highlight: "islands, lagoons, and resort stays" },
  { city: "Melbourne", country: "Australia", highlight: "coffee, galleries, and coastal drives" },
  { city: "Mexico City", country: "Mexico", highlight: "museums, markets, and historic districts" },
  { city: "Miami", country: "United States", highlight: "beaches, nightlife, and Latin food" },
  { city: "Milan", country: "Italy", highlight: "fashion, design, and cathedral views" },
  { city: "Mumbai", country: "India", highlight: "street food, sea views, and film culture" },
  { city: "Munich", country: "Germany", highlight: "beer gardens, museums, and alpine day trips" },
  { city: "New York", country: "United States", highlight: "skyline views, museums, and neighborhoods" },
  { city: "Osaka", country: "Japan", highlight: "food, nightlife, and castle views" },
  { city: "Paris", country: "France", highlight: "museums, cafes, and classic landmarks" },
  { city: "Phuket", country: "Thailand", highlight: "beaches, islands, and night markets" },
  { city: "Prague", country: "Czech Republic", highlight: "old town lanes, castles, and river views" },
  { city: "Queenstown", country: "New Zealand", highlight: "lakes, mountains, and adventure sports" },
  { city: "Reykjavik", country: "Iceland", highlight: "northern lights, lagoons, and road trips" },
  { city: "Rio de Janeiro", country: "Brazil", highlight: "beaches, viewpoints, and music" },
  { city: "Rome", country: "Italy", highlight: "ancient ruins, piazzas, and pasta" },
  { city: "San Francisco", country: "United States", highlight: "bridges, parks, and bay views" },
  { city: "Seoul", country: "South Korea", highlight: "palaces, skincare shopping, and street food" },
  { city: "Singapore", country: "Singapore", highlight: "gardens, shopping, and modern city walks" },
  { city: "Sydney", country: "Australia", highlight: "harbor views, beaches, and coastal walks" },
  { city: "Tokyo", country: "Japan", highlight: "culture, food, technology, and neighborhoods" },
  { city: "Toronto", country: "Canada", highlight: "waterfront, museums, and diverse food" },
  { city: "Udaipur", country: "India", highlight: "lakes, palaces, and romantic city views" },
  { city: "Vancouver", country: "Canada", highlight: "mountains, forests, and waterfront life" },
  { city: "Venice", country: "Italy", highlight: "canals, islands, and historic architecture" },
  { city: "Vienna", country: "Austria", highlight: "palaces, classical music, and cafes" },
  { city: "Zurich", country: "Switzerland", highlight: "lake views, old town, and alpine access" },
];

export const currencies = [
  "AED - United Arab Emirates Dirham", "AFN - Afghan Afghani", "ALL - Albanian Lek", "AMD - Armenian Dram",
  "ANG - Netherlands Antillean Guilder", "AOA - Angolan Kwanza", "ARS - Argentine Peso", "AUD - Australian Dollar",
  "AWG - Aruban Florin", "AZN - Azerbaijani Manat", "BAM - Bosnia-Herzegovina Convertible Mark", "BBD - Barbadian Dollar",
  "BDT - Bangladeshi Taka", "BGN - Bulgarian Lev", "BHD - Bahraini Dinar", "BIF - Burundian Franc",
  "BMD - Bermudian Dollar", "BND - Brunei Dollar", "BOB - Bolivian Boliviano", "BRL - Brazilian Real",
  "BSD - Bahamian Dollar", "BTN - Bhutanese Ngultrum", "BWP - Botswanan Pula", "BYN - Belarusian Ruble",
  "BZD - Belize Dollar", "CAD - Canadian Dollar", "CDF - Congolese Franc", "CHF - Swiss Franc",
  "CLP - Chilean Peso", "CNY - Chinese Yuan", "COP - Colombian Peso", "CRC - Costa Rican Colon",
  "CUP - Cuban Peso", "CVE - Cape Verdean Escudo", "CZK - Czech Koruna", "DJF - Djiboutian Franc",
  "DKK - Danish Krone", "DOP - Dominican Peso", "DZD - Algerian Dinar", "EGP - Egyptian Pound",
  "ERN - Eritrean Nakfa", "ETB - Ethiopian Birr", "EUR - Euro", "FJD - Fijian Dollar",
  "FKP - Falkland Islands Pound", "GBP - British Pound", "GEL - Georgian Lari", "GHS - Ghanaian Cedi",
  "GIP - Gibraltar Pound", "GMD - Gambian Dalasi", "GNF - Guinean Franc", "GTQ - Guatemalan Quetzal",
  "GYD - Guyanese Dollar", "HKD - Hong Kong Dollar", "HNL - Honduran Lempira", "HRK - Croatian Kuna",
  "HTG - Haitian Gourde", "HUF - Hungarian Forint", "IDR - Indonesian Rupiah", "ILS - Israeli New Shekel",
  "INR - Indian Rupee", "IQD - Iraqi Dinar", "IRR - Iranian Rial", "ISK - Icelandic Krona",
  "JMD - Jamaican Dollar", "JOD - Jordanian Dinar", "JPY - Japanese Yen", "KES - Kenyan Shilling",
  "KGS - Kyrgyzstani Som", "KHR - Cambodian Riel", "KMF - Comorian Franc", "KPW - North Korean Won",
  "KRW - South Korean Won", "KWD - Kuwaiti Dinar", "KYD - Cayman Islands Dollar", "KZT - Kazakhstani Tenge",
  "LAK - Lao Kip", "LBP - Lebanese Pound", "LKR - Sri Lankan Rupee", "LRD - Liberian Dollar",
  "LSL - Lesotho Loti", "LYD - Libyan Dinar", "MAD - Moroccan Dirham", "MDL - Moldovan Leu",
  "MGA - Malagasy Ariary", "MKD - Macedonian Denar", "MMK - Myanmar Kyat", "MNT - Mongolian Tugrik",
  "MOP - Macanese Pataca", "MRU - Mauritanian Ouguiya", "MUR - Mauritian Rupee", "MVR - Maldivian Rufiyaa",
  "MWK - Malawian Kwacha", "MXN - Mexican Peso", "MYR - Malaysian Ringgit", "MZN - Mozambican Metical",
  "NAD - Namibian Dollar", "NGN - Nigerian Naira", "NIO - Nicaraguan Cordoba", "NOK - Norwegian Krone",
  "NPR - Nepalese Rupee", "NZD - New Zealand Dollar", "OMR - Omani Rial", "PAB - Panamanian Balboa",
  "PEN - Peruvian Sol", "PGK - Papua New Guinean Kina", "PHP - Philippine Peso", "PKR - Pakistani Rupee",
  "PLN - Polish Zloty", "PYG - Paraguayan Guarani", "QAR - Qatari Riyal", "RON - Romanian Leu",
  "RSD - Serbian Dinar", "RUB - Russian Ruble", "RWF - Rwandan Franc", "SAR - Saudi Riyal",
  "SBD - Solomon Islands Dollar", "SCR - Seychellois Rupee", "SDG - Sudanese Pound", "SEK - Swedish Krona",
  "SGD - Singapore Dollar", "SHP - Saint Helena Pound", "SLE - Sierra Leonean Leone", "SOS - Somali Shilling",
  "SRD - Surinamese Dollar", "SSP - South Sudanese Pound", "STN - Sao Tome and Principe Dobra", "SYP - Syrian Pound",
  "SZL - Swazi Lilangeni", "THB - Thai Baht", "TJS - Tajikistani Somoni", "TMT - Turkmenistani Manat",
  "TND - Tunisian Dinar", "TOP - Tongan Paanga", "TRY - Turkish Lira", "TTD - Trinidad and Tobago Dollar",
  "TWD - New Taiwan Dollar", "TZS - Tanzanian Shilling", "UAH - Ukrainian Hryvnia", "UGX - Ugandan Shilling",
  "USD - United States Dollar", "UYU - Uruguayan Peso", "UZS - Uzbekistani Som", "VES - Venezuelan Bolivar",
  "VND - Vietnamese Dong", "VUV - Vanuatu Vatu", "WST - Samoan Tala", "XAF - Central African CFA Franc",
  "XCD - East Caribbean Dollar", "XOF - West African CFA Franc", "XPF - CFP Franc", "YER - Yemeni Rial",
  "ZAR - South African Rand", "ZMW - Zambian Kwacha", "ZWL - Zimbabwean Dollar",
];
